### ISSUE TITLE
谢谢分享！有一个小建议

### ISSUE THREAD

**Issue by CS-Tao** [vacutice/Image-Matching#2]
**感谢提供项目和实习报告！**

GitHub 一般用于存放源代码，如果存放二进制文件和开发阶段的临时文件，会让项目变得很大，不方便克隆和下载。建议添加一个 `.gitignore` 文件到项目里，[自动生成链接](http://gitignore.io/)。

哎还在下载 🤒

**Comment by vacutice** [comment]
.gitigore我知道，其实我只是懒😂
之前不知道可以自动生成的

**Comment by CS-Tao** [comment]
原来如此 👍
